# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 term will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# i.e., back + front is even
FOUR_MILLION = 4000000000
value = 0
i = 1
back = 0
front = 1
while front+back < FOUR_MILLION:
    temp = front + back;
    back = front
    front = temp
    i += 1
    if i == 3:
        i = 0
        value += front
        print  " front=",front, " back=",back, "value=", value
    else:
        print " front=",front, " back=",back
